@startuml
'https://plantuml.com/use-case-diagram

actor user

usecase createuser
usecase login
usecase menu
usecase categories
usecase titlesearch
usecase watched
usecase saved
usecase add
usecase play
usecase delete
usecase backtomenu
usecase media

top to bottom direction
user -|> createuser
user -|> login

createuser -|> login

login -|> menu

menu <|-left-|> watched
menu <|-right-|> saved
menu <|-up-|> categories
menu <|-down-|> titlesearch

titlesearch -|> media

media -|> play
media -|> add
media <|-|> backtomenu

saved -|> delete
saved -|> play
saved <|-|> backtomenu

watched <|-|> backtomenu
watched -|> play

categories <|-|> backtomenu
categories -|> media

@enduml