@startuml
'https://plantuml.com/object-diagram

object LoginSignupStartmenu
object Menu
object User
object MovieSerie
object SavedList
object Search
object WatchedList
object Play
object Delete
object Add
object Save

LoginSignupStartmenu *-- User

User <--> Menu
'utility.Search <|-- Menu

Menu o-- SavedList
Menu o-- WatchedList
Menu *-- Search

'Saved <|- MovieSerie

'Watched <|- MovieSerie

'Delete' <|- MovieSerie

Search *-- MovieSerie
WatchedList <|-- MovieSerie
SavedList <|-- MovieSerie

MovieSerie *-- Play
Play *-- Save
MovieSerie o-- Delete
MovieSerie *-- Add

Add --|> SavedList
Save --o WatchedList


SavedList --* Delete

'Play-- WatchedList
'Play *-- SavedList

'Menu <|-- Saved
'Menu <|-- Watched
'Menu <|-- Delete
'Menu <|-- utility.Search


@enduml